"""
apply_firma_migration.py
Crea la infraestructura de firma de matrícula (integración con SIMPLE):
- Tabla matriculas.firma_matricula (1 fila por matrícula: solicitud + resultado de firma).
- Columna matricula.estado_firma (badge de estado en la grilla).

Idempotente: usa CREATE TABLE/INDEX IF NOT EXISTS y ADD COLUMN IF NOT EXISTS.
Actúa sobre el schema 'matriculas' vía el search_path del pool de database.py.
"""
import sys
import os

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from database import get_db_connection

DDL_TABLA = """
CREATE TABLE IF NOT EXISTS firma_matricula (
    id_firma           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_matricula       INTEGER REFERENCES matricula(id_matricula),
    simple_tramite_id  TEXT,
    rut_alumno         VARCHAR(20),
    rut_apoderado      VARCHAR(20),
    rut_firmante       VARCHAR(20),
    anio_escolar       INTEGER,
    estado             VARCHAR(20) NOT NULL DEFAULT 'pendiente',
    metodo             VARCHAR(30) DEFAULT 'clave_unica_simple',
    respuestas         JSONB,
    correo_apoderado   VARCHAR(150),
    url_pdf_firmado    TEXT,
    fecha_envio        TIMESTAMPTZ DEFAULT now(),
    fecha_firma        TIMESTAMPTZ,
    created_at         TIMESTAMPTZ DEFAULT now()
);
"""

DDL_INDICES = [
    "CREATE INDEX IF NOT EXISTS idx_firma_matricula_id_mat ON firma_matricula(id_matricula);",
    "CREATE INDEX IF NOT EXISTS idx_firma_matricula_tramite ON firma_matricula(simple_tramite_id);",
    "CREATE UNIQUE INDEX IF NOT EXISTS uq_firma_matricula_tramite ON firma_matricula(simple_tramite_id) WHERE simple_tramite_id IS NOT NULL;",
]

DDL_COLUMNA_ESTADO = "ALTER TABLE matricula ADD COLUMN IF NOT EXISTS estado_firma VARCHAR(20) DEFAULT 'sin_firma';"


def migrate():
    conn = get_db_connection()
    cur = conn.cursor()
    try:
        print("Creando tabla 'firma_matricula' (si no existe)...")
        cur.execute(DDL_TABLA)

        for ddl in DDL_INDICES:
            cur.execute(ddl)
        print("Índices de 'firma_matricula' asegurados.")

        print("Agregando columna 'estado_firma' a 'matricula' (si no existe)...")
        cur.execute(DDL_COLUMNA_ESTADO)

        conn.commit()
        print("Migración de firma aplicada exitosamente.")
    except Exception as e:
        conn.rollback()
        print(f"Error durante la migración de firma: {e}")
        raise
    finally:
        cur.close()
        conn.close()


if __name__ == "__main__":
    migrate()
